package com.jdobf.j2c;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/**
 * 生成 j2c 原生桥接 payload 的 C++ 源码（单翻译单元，MSVC/g++ 均可编译）。
 *
 * 生成内容：
 * <ul>
 *   <li>每个隐藏类一份 XOR 加密的 class 字节码 blob（编译期嵌在 .rdata）；</li>
 *   <li>类名/方法名/描述符等敏感字符串全部 XOR 加密，加载时栈上解密；</li>
 *   <li>每个 native 方法一个零逻辑静态包装器，参数按 jvalue 透传；</li>
 *   <li>首次调用时取 shell 类的 ClassLoader，在其中 DefineClass 复活隐藏类，
 *       缓存 jclass/jmethodID，之后纯转发（CallStatic*MethodA）；</li>
 *   <li>无任何 Java_* 导出、无 JNI_OnLoad：payload 由内存中的 loader 手动
 *       映射，仅导出两个每次构建随机命名的 arm/bind 入口；bind 按 shell
 *       类逐类 RegisterNatives（内存映射镜像无法被 VM 按导出名懒绑定）。</li>
 * </ul>
 */
public final class CppEmitter {

    private CppEmitter() {
    }

    public static final class CMethod {
        public final String name;
        public final String desc;
        public final char ret;       // V/I/J/F/D/L
        public final List<Character> params; // Z B C S I J F D O

        public CMethod(String name, String desc, char ret, List<Character> params) {
            this.name = name;
            this.desc = desc;
            this.ret = ret;
            this.params = params;
        }
    }

    public static final class CClass {
        public final String shellName;
        public final String hiddenName;
        public final byte[] data;
        public final int key;
        public final List<CMethod> methods;
        /** 0 = 首映射镜像，1 = 按需镜像。 */
        public final int group;

        public CClass(String shellName, String hiddenName, byte[] data, int key,
                      List<CMethod> methods, int group) {
            this.shellName = shellName;
            this.hiddenName = hiddenName;
            this.data = data;
            this.key = key;
            this.methods = methods;
            this.group = group;
        }
    }

    /**
     * @param bootAnchor arm 入口被 loader 调用时用来取 ClassLoader 的桥类
     *                   （即 Spec.boot，FindClass 上下文为应用 ClassLoader）
     * @param pullClass  本区复活受阻或 {@code eagerPull} 时回调的静态
     *                   {@code stage2()V} 所在桥类（Spec.map）；镜像2
     *                   重入时其 native mapM2 幂等返回
     * @param eagerPull  1 = arm 复活前先拉起另一镜像（跨区引用无法静态
     *                   切断的场景）；0 = 严格本区复活，另一镜像按需映射
     */
    public static String emit(List<CClass> classesIn, Random random,
                              String armSym, String bindSym,
                              String bootAnchor, String pullClass,
                              boolean eagerPull, boolean vmp) {
        // 依赖类（无 native 方法的簇内成员）排前面，DefineClass 复活时
        // 隐藏代码引用的父/成员类型（如 new Setters$Box$$n）先就位
        List<CClass> classes = new ArrayList<CClass>(classesIn);
        java.util.Collections.sort(classes, new java.util.Comparator<CClass>() {
            @Override
            public int compare(CClass a, CClass b) {
                return (a.methods.isEmpty() ? 0 : 1) - (b.methods.isEmpty() ? 0 : 1);
            }
        });

        // ---- 字符串表（XOR 加密） ----
        List<String> strings = new ArrayList<String>();
        strings.add("java/lang/Class");
        strings.add("getClassLoader");
        strings.add("()Ljava/lang/ClassLoader;");
        strings.add("getName");
        strings.add("()Ljava/lang/String;");
        // arm 锚点类 / 跨区拉起回调（stage2）
        strings.add(bootAnchor);
        strings.add(pullClass);
        strings.add("stage2");
        strings.add("()V");
        List<Integer> sKeys = new ArrayList<Integer>();
        for (String ignored : strings) {
            sKeys.add(1 + random.nextInt(254));
        }
        int[] shellStr = new int[classes.size()];
        int[] hiddenStr = new int[classes.size()];
        int[][][] methodStr = new int[classes.size()][][];
        for (int ci = 0; ci < classes.size(); ci++) {
            CClass cc = classes.get(ci);
            shellStr[ci] = addString(strings, sKeys, cc.shellName, random);
            hiddenStr[ci] = addString(strings, sKeys, cc.hiddenName, random);
            methodStr[ci] = new int[cc.methods.size()][2];
            for (int mi = 0; mi < cc.methods.size(); mi++) {
                CMethod m = cc.methods.get(mi);
                methodStr[ci][mi][0] = addString(strings, sKeys, m.name, random);
                methodStr[ci][mi][1] = addString(strings, sKeys, m.desc, random);
            }
        }

        StringBuilder sb = new StringBuilder(65536);
        sb.append("/* Generated by Doubao Obfuscator j2c bridge. Do not edit. */\n");
        sb.append("#include \"vmpmark.h\"\n");
        sb.append("#include <jni.h>\n");
        sb.append("#include <cstdlib>\n");
        sb.append("#include <cstring>\n");
        sb.append("#include <mutex>\n\n");
        sb.append("typedef unsigned char u8;\n\n");

        // ---- 字符串数组 ----
        for (int i = 0; i < strings.size(); i++) {
            byte[] raw = strings.get(i).getBytes(java.nio.charset.StandardCharsets.UTF_8);
            int k = sKeys.get(i);
            sb.append("static const u8 SS_").append(i).append("[] = {");
            appendBytes(sb, xor(raw, k, 17));
            sb.append("};\n");
        }
        sb.append("\nstruct SEnt { u8 k; int n; const u8* p; };\n");
        sb.append("static const SEnt STR[").append(strings.size()).append("] = {\n");
        for (int i = 0; i < strings.size(); i++) {
            byte[] raw = strings.get(i).getBytes(java.nio.charset.StandardCharsets.UTF_8);
            sb.append("  {").append(sKeys.get(i)).append(',').append(raw.length)
                    .append(",SS_").append(i).append("},\n");
        }
        sb.append("};\n\n");

        // ---- blob 数组 ----
        for (int ci = 0; ci < classes.size(); ci++) {
            CClass cc = classes.get(ci);
            byte[] enc = xor(cc.data, cc.key, 31);
            sb.append("static const u8 BB_").append(ci).append("[] = {");
            appendBytes(sb, enc);
            sb.append("};\n");
        }
        sb.append('\n');

        int totalMethods = 0;
        for (CClass cc : classes) {
            totalMethods += cc.methods.size();
        }

        sb.append("struct CEnt { int sm; int hm; const u8* blob; size_t len; u8 key; ")
                .append("int m0; int mn; };\n");
        sb.append("static const CEnt CLS[").append(classes.size()).append("] = {\n");
        int mCursor = 0;
        for (int ci = 0; ci < classes.size(); ci++) {
            CClass cc = classes.get(ci);
            sb.append("  {").append(shellStr[ci]).append(',')
                    .append(hiddenStr[ci])
                    .append(",BB_").append(ci).append(',')
                    .append(cc.data.length).append(',').append(cc.key & 255).append(',')
                    .append(mCursor).append(',').append(cc.methods.size()).append("},\n");
            mCursor += cc.methods.size();
        }
        sb.append("};\n\n");

        sb.append("struct MEnt { int ci; int nm; int ds; u8 ret; };\n");
        sb.append("static const MEnt MET[").append(Math.max(1, totalMethods)).append("] = {\n");
        for (int ci = 0; ci < classes.size(); ci++) {
            CClass cc = classes.get(ci);
            for (int mi = 0; mi < cc.methods.size(); mi++) {
                CMethod m = cc.methods.get(mi);
                sb.append("  {").append(ci).append(',')
                        .append(methodStr[ci][mi][0]).append(',')
                        .append(methodStr[ci][mi][1]).append(",'")
                        .append(m.ret).append("'},\n");
            }
        }
        sb.append("};\n\n");

        sb.append("static jclass g_hc[").append(Math.max(1, classes.size()))
                .append("];\n");
        sb.append("static jmethodID g_mid[").append(Math.max(1, totalMethods))
                .append("];\n");
        sb.append("static jmethodID g_gcl = 0;\n");
        sb.append("static jobject g_ldr = 0;\n");
        sb.append("static std::mutex g_mu;\n");
        sb.append("static volatile int g_ready = 0;\n\n");

        // ---- 解密辅助 ----
        // noinline：VMP 构建时防止编译器把带字节循环的 dstr 内联进被标记
        // 函数（内联副本的 AVX-512 向量化会让 VMProtect 反汇编失败）
        sb.append("J2C_NOINLINE static char* dstr(int idx, char* buf) {\n");
        sb.append("  const SEnt& s = STR[idx];\n");
        sb.append("  VMP_NOVEC\n");
        sb.append("  for (int i = 0; i < s.n; i++) ")
                .append("buf[i] = (char)(s.p[i] ^ (u8)((s.k + i * 17) & 255));\n");
        sb.append("  buf[s.n] = 0;\n  return buf;\n}\n\n");

        // ---- 复活引擎：arm 被 loader 调用时立即跑一遍（锚点为 boot 桥类），
        //      wrapper 首次调用时再兜底。绝不在 JNI_OnLoad 里
        //      FindClass/RegisterNatives：payload 是手动映射镜像，没有
        //      JNI_OnLoad 生命周期。
        // 取锚点类（boot 桥或 shell）的 ClassLoader，全局缓存
        sb.append("static jobject getLoader(JNIEnv* e, jobject anchor) {\n");
        sb.append("  if (g_ldr) return g_ldr;\n");
        sb.append("  jclass jlc = e->FindClass(\"java/lang/Class\");\n");
        sb.append("  if (!jlc) { e->ExceptionClear(); return 0; }\n");
        sb.append("  char gb[64], gd[64];\n");
        sb.append("  g_gcl = e->GetMethodID(jlc, dstr(1, gb), dstr(2, gd));\n");
        sb.append("  if (!g_gcl) return 0;\n");
        sb.append("  jobject l = e->CallObjectMethod(anchor, g_gcl);\n");
        sb.append("  if (e->ExceptionCheck()) { e->ExceptionClear(); return 0; }\n");
        sb.append("  if (!l) return 0;\n");
        sb.append("  g_ldr = e->NewGlobalRef(l);\n");
        sb.append("  return g_ldr;\n}\n\n");
        // 跨区拉起：回调 M.stage2()，映射并复活另一镜像（幂等：镜像2
        // 映射中途重入 mapM2 直接返回；异常全部吞掉由后续 DefineClass
        // 自然暴露真实错误）
        sb.append("static void pullOther(JNIEnv* e) {\n");
        sb.append("  char pc[300], nm[64], ds[64];\n");
        sb.append("  dstr(6, pc); dstr(7, nm); dstr(8, ds);\n");
        sb.append("  jclass c = e->FindClass(pc);\n");
        sb.append("  if (!c) { e->ExceptionClear(); return; }\n");
        sb.append("  jmethodID mid = e->GetStaticMethodID(c, nm, ds);\n");
        sb.append("  if (!mid) { e->ExceptionClear(); return; }\n");
        sb.append("  e->CallStaticVoidMethod(c, mid);\n");
        sb.append("  if (e->ExceptionCheck()) e->ExceptionClear();\n}\n\n");
        // 多趟 DefineClass 复活本区全部隐藏类；卡住时回调一次另一镜像
        sb.append("static int pump(JNIEnv* e, jobject anchor) {\n");
        if (vmp) {
            sb.append("  VMP_BEGIN_MUT(\"pump\");\n");
        }
        sb.append("  if (g_ready) return 1;\n");
        sb.append("  std::lock_guard<std::mutex> lk(g_mu);\n");
        sb.append("  if (g_ready) return 1;\n");
        sb.append("  jobject loader = getLoader(e, anchor);\n");
        sb.append("  if (!loader) return 0;\n");
        if (eagerPull) {
            // 分区无法静态切断跨区引用：boot 时就把镜像2 一并拉起
            sb.append("  pullOther(e);\n");
        }
        sb.append("  int remain = ").append(classes.size()).append(";\n");
        sb.append("  int guard = 0, pulled = 0;\n");
        // 隐藏类的超类/nest 主机/引用类型可能也是尚未定义的隐藏类，
        // 且它们在 jar 中没有资源，无法被加载器按需加载。多趟重试直到
        // 定义闭包；真正的非法字节最终再 DefineClass 一次，把异常交给 JVM。
        sb.append("  while (remain > 0) {\n");
        sb.append("    bool progress = false;\n");
        sb.append("    for (int ci = 0; ci < ").append(classes.size()).append("; ci++) {\n");
        sb.append("      if (g_hc[ci]) continue;\n");
        sb.append("      const CEnt& ce = CLS[ci];\n");
        sb.append("      u8* buf = (u8*)malloc(ce.len);\n");
        sb.append("      if (!buf) return 0;\n");
        sb.append("      VMP_NOVEC\n");
        sb.append("      for (size_t i = 0; i < ce.len; i++) ")
                .append("buf[i] = ce.blob[i] ^ (u8)((ce.key + i * 31) & 255);\n");
        sb.append("      char cn[300]; dstr(ce.hm, cn);\n");
        sb.append("      jclass def = e->DefineClass(cn, loader, ")
                .append("(const jbyte*)buf, (jsize)ce.len);\n");
        sb.append("      free(buf);\n");
        sb.append("      if (def) {\n");
        sb.append("        g_hc[ci] = (jclass)e->NewGlobalRef(def);\n");
        sb.append("        remain--; progress = true;\n");
        sb.append("      } else {\n");
        sb.append("        // prerequisite hidden super/nest class not defined yet; retry\n");
        sb.append("        e->ExceptionClear();\n");
        sb.append("      }\n");
        sb.append("    }\n");
        sb.append("    if (remain > 0 && !progress && !pulled) {\n");
        sb.append("      pulled = 1; pullOther(e); guard++;\n");
        sb.append("      continue;\n");
        sb.append("    }\n");
        sb.append("    if (!progress || ++guard > ").append(classes.size())
                .append(" + 2) break;\n");
        sb.append("  }\n");
        sb.append("  if (remain == 0) { g_ready = 1; return 1; }\n");
        sb.append("  for (int ci = 0; ci < ").append(classes.size()).append("; ci++) {\n");
        sb.append("      if (g_hc[ci]) continue;\n");
        sb.append("      const CEnt& ce = CLS[ci];\n");
        sb.append("      u8* buf = (u8*)malloc(ce.len);\n");
        sb.append("      if (!buf) return 0;\n");
        sb.append("      VMP_NOVEC\n");
        sb.append("      for (size_t i = 0; i < ce.len; i++) ")
                .append("buf[i] = ce.blob[i] ^ (u8)((ce.key + i * 31) & 255);\n");
        sb.append("      char cn[300]; dstr(ce.hm, cn);\n");
        sb.append("      e->DefineClass(cn, loader, (const jbyte*)buf, (jsize)ce.len);\n");
        sb.append("      free(buf);\n");
        sb.append("      return 0; // real ClassFormatError/NoClassDefFoundError: surface to JVM\n");
        sb.append("    }\n");
        sb.append("  g_ready = 1;\n  VMP_END();\n  return 1;\n}\n\n");

        // wrapper 首次调用兜底（正常路径 arm 已复活完毕）
        sb.append("static void ensureReady(JNIEnv* e, jclass shell) {\n");
        sb.append("  if (g_ready) return;\n");
        sb.append("  pump(e, shell);\n}\n\n");

        sb.append("static jmethodID resolve(JNIEnv* e, int mi) {\n");
        sb.append("  if (g_mid[mi]) return g_mid[mi];\n");
        sb.append("  const MEnt& me = MET[mi];\n");
        sb.append("  char nb[256], ds[1024];\n");
        sb.append("  dstr(me.nm, nb); dstr(me.ds, ds);\n");
        sb.append("  g_mid[mi] = e->GetStaticMethodID(g_hc[me.ci], nb, ds);\n");
        sb.append("  return g_mid[mi];\n}\n\n");

        // ---- 六类转发 ----
        sb.append("static jint dI(JNIEnv* e, jclass s, int mi, jvalue* v) {\n")
                .append("  ensureReady(e, s); jmethodID id = resolve(e, mi);\n")
                .append("  return e->CallStaticIntMethodA(g_hc[MET[mi].ci], id, v); }\n");
        sb.append("static jlong dJ(JNIEnv* e, jclass s, int mi, jvalue* v) {\n")
                .append("  ensureReady(e, s); jmethodID id = resolve(e, mi);\n")
                .append("  return e->CallStaticLongMethodA(g_hc[MET[mi].ci], id, v); }\n");
        sb.append("static jfloat dF(JNIEnv* e, jclass s, int mi, jvalue* v) {\n")
                .append("  ensureReady(e, s); jmethodID id = resolve(e, mi);\n")
                .append("  return e->CallStaticFloatMethodA(g_hc[MET[mi].ci], id, v); }\n");
        sb.append("static jdouble dD(JNIEnv* e, jclass s, int mi, jvalue* v) {\n")
                .append("  ensureReady(e, s); jmethodID id = resolve(e, mi);\n")
                .append("  return e->CallStaticDoubleMethodA(g_hc[MET[mi].ci], id, v); }\n");
        sb.append("static void dV(JNIEnv* e, jclass s, int mi, jvalue* v) {\n")
                .append("  ensureReady(e, s); jmethodID id = resolve(e, mi);\n")
                .append("  e->CallStaticVoidMethodA(g_hc[MET[mi].ci], id, v); }\n");
        sb.append("static jobject dL(JNIEnv* e, jclass s, int mi, jvalue* v) {\n")
                .append("  ensureReady(e, s); jmethodID id = resolve(e, mi);\n")
                .append("  return e->CallStaticObjectMethodA(g_hc[MET[mi].ci], id, v); }\n\n");

        // ---- 每方法静态包装器（不导出；由 bind 时的 RegisterNatives 表
        //      取函数地址绑定）。bind 从 shell 自身 <clinit> 触发，只注册
        //      当前类，不 FindClass 其他 shell，无重入；隐藏类 DefineClass
        //      仍延迟到第一次方法调用（ensureReady）。 ----
        int wi = 0;
        for (int ci = 0; ci < classes.size(); ci++) {
            CClass cc = classes.get(ci);
            for (int mi = 0; mi < cc.methods.size(); mi++, wi++) {
                CMethod m = cc.methods.get(mi);
                sb.append("static ").append(jniReturn(m.ret))
                        .append(" JNICALL w_").append(wi)
                        .append("(JNIEnv* e, jclass c");
                for (int pi = 0; pi < m.params.size(); pi++) {
                    sb.append(", ").append(jniType(m.params.get(pi))).append(' ').append('p')
                            .append(pi);
                }
                sb.append(") {\n");
                if (vmp) {
                    // 每构建随机的保护档位：约 1/5 Ultra（虚拟化+变异）、
                    // 3/10 虚拟化、1/2 变异。包装器是单出口直线函数，
                    // 任意档位语义都安全，且让每构建形态不同。
                    int roll = random.nextInt(10);
                    String kind = roll < 2 ? "ULTRA" : roll < 5 ? "VIRT" : "MUT";
                    sb.append("  VMP_BEGIN_").append(kind)
                            .append("(\"w").append(wi).append("\");\n");
                }
                int n = m.params.size();
                sb.append("  jvalue v[").append(Math.max(1, n)).append("];\n");
                for (int pi = 0; pi < n; pi++) {
                    sb.append("  v[").append(pi).append("].")
                            .append(jvalueField(m.params.get(pi))).append(" = p").append(pi)
                            .append(";\n");
                }
                if (vmp && m.ret != 'V') {
                    // 单出口：先接结果，End 标记可达，再返回
                    sb.append("  ").append(jniReturn(m.ret)).append(" vr = ")
                            .append(jniDispatchNoReturn(m.ret, wi)).append(";\n");
                    sb.append("  VMP_END();\n");
                    sb.append("  return vr;\n");
                } else if (vmp) {
                    sb.append("  ").append(jniDispatch(m.ret, wi)).append(";\n");
                    sb.append("  VMP_END();\n");
                } else {
                    sb.append("  ").append(jniDispatch(m.ret, wi)).append(";\n");
                }
                sb.append("}\n\n");
            }
        }

        // ---- 函数表：bind 时每类一段注册给 RegisterNatives ----
        sb.append("struct FEnt { int nm; int ds; void* fp; };\n");
        sb.append("static const FEnt FNS[").append(Math.max(1, totalMethods))
                .append("] = {\n");
        wi = 0;
        for (int ci = 0; ci < classes.size(); ci++) {
            CClass cc = classes.get(ci);
            for (int mi = 0; mi < cc.methods.size(); mi++, wi++) {
                sb.append("  {").append(methodStr[ci][mi][0]).append(',')
                        .append(methodStr[ci][mi][1]).append(",(void*)&w_")
                        .append(wi).append("},\n");
            }
        }
        sb.append("};\n\n");

        // ---- 逐类绑定：loader 手动映射后调用 arm；每个 shell 的 <clinit>
        //      再经 loader 调 bind(Class)。getName 的 '.' 还原成 '/' 后与
        //      加密 shell 名比较，注册该类全部 native，名字/签名缓冲按
        //      STR 实际长度分配。 ----
        sb.append("static jint doBind(JNIEnv* e, jobject shellCls) {\n");
        if (vmp) {
            sb.append("  VMP_BEGIN_MUT(\"doBind\");\n");
        }
        sb.append("  jclass jlc = e->FindClass(\"java/lang/Class\");\n");
        sb.append("  if (!jlc) return 0;\n");
        sb.append("  static jmethodID g_gn = 0;\n");
        sb.append("  if (!g_gn) {\n");
        sb.append("    char nb[64], ds[96]; dstr(3, nb); dstr(4, ds);\n");
        sb.append("    g_gn = e->GetMethodID(jlc, nb, ds);\n");
        sb.append("  }\n");
        sb.append("  if (!g_gn) return 0;\n");
        sb.append("  jstring jn = (jstring)e->CallObjectMethod(shellCls, g_gn);\n");
        sb.append("  if (!jn) return 0;\n");
        sb.append("  const char* raw = e->GetStringUTFChars(jn, 0);\n");
        sb.append("  if (!raw) return 0;\n");
        sb.append("  char want[512];\n");
        sb.append("  size_t rl = strlen(raw);\n");
        sb.append("  if (rl >= 511) { e->ReleaseStringUTFChars(jn, raw); return 0; }\n");
        sb.append("  size_t k = 0;\n");
        sb.append("  VMP_NOVEC\n");
        sb.append("  for (size_t i = 0; i < rl; i++) {\n");
        sb.append("    char ch = raw[i]; want[k++] = (ch == '.') ? '/' : ch;\n");
        sb.append("  }\n");
        sb.append("  want[k] = 0;\n");
        sb.append("  e->ReleaseStringUTFChars(jn, raw);\n");
        sb.append("  for (int ci = 0; ci < ").append(classes.size()).append("; ci++) {\n");
        sb.append("    char sn[512]; dstr(CLS[ci].sm, sn);\n");
        sb.append("    if (strcmp(sn, want) != 0) continue;\n");
        sb.append("    int m0 = CLS[ci].m0, mn = CLS[ci].mn;\n");
        sb.append("    if (mn == 0) return 1;\n");
        sb.append("    JNINativeMethod* ms = (JNINativeMethod*)malloc(")
                .append("(size_t)mn * sizeof(JNINativeMethod));\n");
        sb.append("    char** nbufs = (char**)malloc((size_t)mn * sizeof(char*));\n");
        sb.append("    char** sbufs = (char**)malloc((size_t)mn * sizeof(char*));\n");
        sb.append("    if (!ms || !nbufs || !sbufs) {\n");
        sb.append("      free(ms); free(nbufs); free(sbufs); return 0;\n");
        sb.append("    }\n");
        sb.append("    for (int t = 0; t < mn; t++) {\n");
        sb.append("      const FEnt& fe = FNS[m0 + t];\n");
        sb.append("      nbufs[t] = (char*)malloc(STR[fe.nm].n + 1);\n");
        sb.append("      sbufs[t] = (char*)malloc(STR[fe.ds].n + 1);\n");
        sb.append("      if (!nbufs[t] || !sbufs[t]) {\n");
        sb.append("        for (int u = 0; u <= t; u++) { free(nbufs[u]); free(sbufs[u]); }\n");
        sb.append("        free(ms); free(nbufs); free(sbufs); return 0;\n");
        sb.append("      }\n");
        sb.append("      dstr(fe.nm, nbufs[t]); dstr(fe.ds, sbufs[t]);\n");
        sb.append("      ms[t].name = nbufs[t]; ms[t].signature = sbufs[t]; ")
                .append("ms[t].fnPtr = fe.fp;\n");
        sb.append("    }\n");
        sb.append("    jint rc = e->RegisterNatives((jclass)shellCls, ms, mn);\n");
        sb.append("    for (int t = 0; t < mn; t++) { free(nbufs[t]); free(sbufs[t]); }\n");
        sb.append("    free(ms); free(nbufs); free(sbufs);\n");
        sb.append("    return rc == 0 ? 1 : 0;\n");
        sb.append("  }\n");
        // 2 = 该 shell 不属于本镜像：Java 路由层改调另一镜像的 bind
        sb.append("  VMP_END();\n  return 2;\n}\n\n");

        // ---- 仅有的两个导出，名字每构建随机；JNI_OnLoad 刻意不存在 ----
        // arm：loader 手动映射成功后调用，立即用 boot 桥类的 ClassLoader
        // 多趟 DefineClass 复活本区全部隐藏类
        sb.append("extern \"C\" JNIEXPORT jint JNICALL ").append(armSym)
                .append("(JavaVM* vm, void* r) {\n");
        if (vmp) {
            sb.append("  VMP_BEGIN_MUT(\"arm\");\n");
        }
        sb.append("  (void)r;\n");
        sb.append("  JNIEnv* e = 0;\n");
        sb.append("  if (vm->GetEnv((void**)&e, JNI_VERSION_1_8) != 0 || !e) return 0;\n");
        sb.append("  char an[300]; dstr(5, an);\n");
        sb.append("  jclass anchor = e->FindClass(an);\n");
        sb.append("  if (!anchor) { e->ExceptionClear(); return 0; }\n");
        sb.append("  if (!pump(e, anchor)) return 0;\n");
        if (vmp) {
            sb.append("  VMP_END();\n");
        }
        sb.append("  return JNI_VERSION_1_8;\n}\n\n");
        sb.append("extern \"C\" JNIEXPORT jint JNICALL ").append(bindSym)
                .append("(JNIEnv* e, jclass bc, jobject shellCls) {\n");
        sb.append("  (void)bc;\n");
        if (vmp) {
            sb.append("  VMP_BEGIN_MUT(\"bind\");\n");
            sb.append("  jint br = doBind(e, shellCls);\n");
            sb.append("  VMP_END();\n");
            sb.append("  return br;\n}\n");
        } else {
            sb.append("  return doBind(e, shellCls);\n}\n");
        }
        return sb.toString();
    }

    private static int addString(List<String> strings, List<Integer> keys,
                                 String s, Random random) {
        strings.add(s);
        keys.add(1 + random.nextInt(254));
        return strings.size() - 1;
    }

    private static byte[] xor(byte[] raw, int key, int mul) {
        byte[] out = new byte[raw.length];
        for (int i = 0; i < raw.length; i++) {
            out[i] = (byte) (raw[i] ^ ((key + i * mul) & 255));
        }
        return out;
    }

    private static void appendBytes(StringBuilder sb, byte[] data) {
        for (int i = 0; i < data.length; i++) {
            if (i % 16 == 0) {
                sb.append("\n  ");
            }
            sb.append('0').append('x');
            int v = data[i] & 255;
            if (v < 16) {
                sb.append('0');
            }
            sb.append(Integer.toHexString(v)).append(',');
        }
        if (data.length > 0) {
            sb.append('\n');
        }
    }

    private static String jniReturn(char ret) {
        switch (ret) {
            case 'V': return "void";
            case 'J': return "jlong";
            case 'F': return "jfloat";
            case 'D': return "jdouble";
            case 'L': return "jobject";
            default:  return "jint";
        }
    }

    private static String jniType(char p) {
        switch (p) {
            case 'Z': return "jboolean";
            case 'B': return "jbyte";
            case 'C': return "jchar";
            case 'S': return "jshort";
            case 'J': return "jlong";
            case 'F': return "jfloat";
            case 'D': return "jdouble";
            case 'O': return "jobject";
            default:  return "jint";
        }
    }

    private static char jvalueField(char p) {
        switch (p) {
            case 'Z': return 'z';
            case 'B': return 'b';
            case 'C': return 'c';
            case 'S': return 's';
            case 'J': return 'j';
            case 'F': return 'f';
            case 'D': return 'd';
            case 'O': return 'l';
            default:  return 'i';
        }
    }

    private static String jniDispatch(char ret, int wi) {
        switch (ret) {
            case 'V': return "dV(e, c, " + wi + ", v)";
            case 'J': return "return dJ(e, c, " + wi + ", v)";
            case 'F': return "return dF(e, c, " + wi + ", v)";
            case 'D': return "return dD(e, c, " + wi + ", v)";
            case 'L': return "return dL(e, c, " + wi + ", v)";
            default:  return "return dI(e, c, " + wi + ", v)";
        }
    }

    /** 与 {@link #jniDispatch} 相同的转发调用，但不含 return 前缀。 */
    private static String jniDispatchNoReturn(char ret, int wi) {
        String s = jniDispatch(ret, wi);
        return s.startsWith("return ") ? s.substring(7) : s;
    }
}
